version: '3'

services:

  hydra-migrate:
    image: oryd/hydra:latest
    environment:
      - DSN=postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
    command:
      migrate sql -e --yes
    restart: on-failure

  postgresd:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=hydra

  hydra:
    depends_on:
      - hydra-migrate
    image: oryd/hydra:latest
    container_name: sso-demo-hydra
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
      - "5555:5555" # Port for hydra token user
    command:
      serve all --dangerous-force-http
    environment:
      - DSN=postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
      - SERVE_PUBLIC_CORS_ENABLED=true
      - LOG_LEVEL=debug
      - SERVE_PUBLIC_CORS_DEBUG=true
      - SERVE_PUBLIC_CORS_ALLOWED_ORIGINS=*
      - SERVE_ADMIN_CORS_ENABLED=true
      - SERVE_ADMIN_CORS_DEBUG=true
      - SERVE_ADMIN_CORS_ALLOWED_ORIGINS=*
      - CORS_ALLOWED_ORIGINS=*
      - URLS_SELF_ISSUER=http://127.0.0.1:4444/
      - URLS_CONSENT=http://localhost:8087/v1/consent
      - URLS_LOGIN=http://localhost:8087/v1/login
      - URLS_LOGOUT=http://localhost:8087/v1/logout
      - SECRETS_SYSTEM=IamTheOnlyAuthProviderArround1
      - OIDC_SUBJECT_TYPES_SUPPORTED=public,pairwise
      - OIDC_SUBJECT_TYPE_PAIRWISE_SALT=AndThisIsMySaltedConfig
    restart: unless-stopped


